name: Deploy to Home Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to remote server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          # Navigate to your project directory
          cd /home/${{ secrets.USERNAME }}/Desktop/algo-trade-devops

          
          # Pull latest changes
          git pull origin main
          
          # Stop existing containers
          docker compose down
          
          # Rebuild and start containers
          docker compose build
          
          # Optional: Clean up unused images
          docker image prune -f